### ISSUE TITLE
x11gost & Sib

### ISSUE THREAD

**Issue by Pititul** [nemosminer/NemosMiner-v2.2.2#52]
I think x11gost & Sib are the same... ? They are both listed in the miner.ps1.

**Comment by nemosminer** [comment]
yes nicehash uses x11gost as algo name where Zpool uses Sib as algo name?? 

are you having a issue with this??

**Comment by nemosminer** [comment]
yes nicehash uses x11gost as algo name and zpool uses sib..

**Comment by nemosminer** [comment]
its working for zpool i think i need to add sib - x11gost in Algo.txt for nicehash

**Comment by nemosminer** [comment]
well no nicehash anymore so we good !
