### ISSUE TITLE
Delay and worker id

### ISSUE THREAD

**Issue by airwalker1** [nemosminer/NemosMiner-v2.2.2#58]
Please add the ability to change worker ID in the batch. I have multiple rigs and it helps identify as well as correct the difficulty when benchmarking.

Also a feature that helps with crashing is adding a delay option between miner starts. Sniffdog's port has it if you can look at it.

**Comment by nemosminer** [comment]
sure i can add worker id: to start.bat

"[Int]$Delay = 1 #seconds before opening each miner"


there already is a option coded into the NemosMiner.ps1 for delay between switching miners its currently set to 1sec .... Sniffdog is forked from NemosMiner....

**Comment by happyartifact** [comment]
All my workers have an ID of NemosMiner-v2.2.1.  I can't see a way to change that to something meaningful.  Is there a way?
