### ISSUE TITLE
How do I mine with MiningPoolHub with this?

### ISSUE THREAD

**Issue by winnal** [nemosminer/NemosMiner-v2.2.2#61]
How do I mine with MiningPoolHub with this?

**Comment by nemosminer** [comment]
Create Account https://miningpoolhub.com / add worker

edit: startminingpoolhub.bat

1.change Username and WorkerName to yours 

2.select how many gpu's you have eg: (1gpu ewbf 0 cc 0) (default 2 gpu ewbf 0 1 cc 0,1) (6gpu ewbf 0 1 2 3 4 5 cc 0,1,2,3,4,5)

3.remove any algos you do not want to mine (default all supported algos enabled)

4.there is a default 5minute per day fee, that can be disabled by changing -Donate 5 to 0

5.run startminingpoolhub.bat

Best Regards
Nemo

**Comment by newmember27** [comment]
I changed the username from nemo to the one I'm using and added the workers that I assigned instead of the miningpoolhub. I keep getting "failed" on the status section instead of "running"
