### ISSUE TITLE
How do you calculate BTC/Day?

### ISSUE THREAD

**Issue by thebitbrine** [nemosminer/NemosMiner-v2.2.2#62]
Hi there,
I'm applying some tweaks to your code to add more miners and algorithms and fix some bugs in C#.
As of right now i do use some of your logic from your code that i converted to C#.
For some reasons i'm not able to convert your whole code with the converter i use,
because its actually a C# to PowerShell converter but it does some reverse conversions,
So i'll be able to convert my code to PowerShell later for pushing purposes.
Right now the only problem i have is about calculating the profitability of a coin/algorithm. 
As i am not a `PowerShell` expert i can't exactly understand how you do calculate the profitability from hashrate.

Any clues, suggestions, info, snippets, APIs, Online conversions tools, etc will be much appreciated :smile: 

Thanks.

**Comment by rvwoens** [comment]
actually it does not calculate it but downloads it from zpool.ca through their api.
