### ISSUE TITLE
400% increase in hashrate gtx 1070  cryptonight

### ISSUE THREAD

**Issue by zxhaxdr** [nemosminer/NemosMiner-v2.2.2#68]
I did some tests and it seems that  if I use ccminer tpruvot x64 version, I can get 640h/s for cryptonight for GTX1070 without invalid shares, but the original x86 from your repo will only get 100h/s. However P106-100 cards works fine with x86 version.

**Comment by nemosminer** [comment]
thanks ill sort cryptonight algo out soon

**Comment by nemosminer** [comment]
thankyou my single gtx 1070 test rig

has gone from 110h/s  to  630h/s 
500% increase in hash rate same ccminer tpruvot 2.2.3 just use 64bit instead of 32bit

**Comment by zxhaxdr** [comment]
Nice work! Thank you for updating. Should I just leave this open, or you can just close it :).

**Comment by nemosminer** [comment]
also add -i 10 to fix out of memory issue

**Comment by zxhaxdr** [comment]
I used default intensity but " -l 40x32" for P106-100(GTX1060) and " -l 120x16" for GTX1070. The improvement for gtx1060 is massive. For other models just look the core architecture (I guess), for example, 80x32 for GP104(GTX1080).  You can try it.
