### ISSUE TITLE
ccminer_nanshi 2.2 - 5-10% improvement in Lyra2REv2

### ISSUE THREAD

**Issue by maxgamurar** [nemosminer/NemosMiner-v2.2.2#72]
It would be nice to have ccminer_nanshi 2.2:

    5-10% improvement in Lyra2REv2

yeh 5-10% faster than Tpruvot....  my included Alexis78 is already faster by quite a bit... no upgrade here would be a downgrade

**Comment by nemosminer** [comment]
proof? which cards?

**Comment by maxgamurar** [comment]
nvidia cards

**Comment by maxgamurar** [comment]
@nemosminer  check this http://cryptomining-blog.com/9166-latest-ccminer-2-2-fork-by-nanashi-meiyo-meijin-for-monacoin-mining/

**Comment by nemosminer** [comment]
i mean proof as in screen shot of you running it faster than my current miner? i have tested it myself i know it to be slower...  with 1060's 1070 1070ti's and 1080;s 

(which "nvidia cards" cards are you referring to)?

**Comment by UselessGuru** [comment]
@nemosminer 

It is faster on my MSI GTX1070 Armor (PL90%/OC+175/MOC+225):
Ccminer-2.2-mod-r2     Lyra2RE2               41.25 MH/s
CcminerPalgin-Nist5     Lyra2RE2               38.10 MH/s

On my GTX1060 3GB & 1080TI CcminerPalgin-Nist5 ist about 2% faster than Ccminer-2.2-mod-r2

**Comment by nemosminer** [comment]
@UselessGuru 
have you tested it against my current lyra2v2 miner ? Alexis is faster than both... Palgin and 2.2-mod-r2 as far as i recall i have tested it myself

**Comment by coreshift** [comment]
Are both of you looking at miner or pool hashrate? Because a number of people have reported problems with pool hashrates being significantly lower than miner reported for some lyra2v2 miners. I vaguely recall something about some miners not reporting shares to the pool correctly.

**Comment by nemosminer** [comment]
speed in miner console is what i use... not speed at pool as that can vary alot

**Comment by UselessGuru** [comment]
@NemosMiner

> have you tested it against [my current lyra2v2 miner](https://github.com/nemosminer/ccminer-hcash/releases/download/alexishsr/ccminer-hsr-alexis-x86-cuda8.7z) ?

I can confirm that your miner is approx 5-10% faster:
GTX 1080TI (PL: 90%, OC: +75, MOC: +200, P-State: 0)
CcminerAlexis78hsr 67.01 MH/s
CcminerPalgin-Nist5 62.01 MH/s
GTX1070 (PL: 90%, OC: +100, MOC: +300, P-State: 0)
CcminerAlexis78hsr 40.03 MH/s
CcminerPalgin-Nist5 37.14 MH/s
GTX10603GB (PL: 90%, OC: +150, MOC: +600, P-State: 0)
CcminerAlexis78hsr 24.68 MH/s
CcminerPalgin-Nist5 20.84 MH/s

Thank you for the hit with your miner - only 3.5232 * 10^4 days left until I become a millionaire from mining :-)

**Comment by nemosminer** [comment]
glad to help

**Comment by byu123** [comment]
I get 73-75 MHS on 1080ti with Alexis.  ccminer-Alexis78 is fastest of all flavors.

**Comment by pralenka** [comment]
i can get 28.5mhs with 1060 3gb oc + 110 coreclock +500memory
