### ISSUE TITLE
CryptoNight Failure

### ISSUE THREAD

**Issue by joesixpack** [nemosminer/NemosMiner-v2.2.2#75]
The CryptoNight benchmark is failing.  Does not launch at all.  Miner is there in bin.

**Comment by nemosminer** [comment]
thanks checking now

**Comment by Gercoli** [comment]
This was also happening to me, so I decided to run the command manually for the cryptonight benchmark, this is what I got:

>[2017-12-15 10:19:08] Using JSON-RPC 2.0
[2017-12-15 10:19:08] Starting on stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:17024
[2017-12-15 10:19:08] NVAPI GPU monitoring enabled.
[2017-12-15 10:19:08] 1 miner thread started, using 'cryptonight' algorithm.
[2017-12-15 10:19:09] Stratum difficulty set to 500054 (500.054)
[2017-12-15 10:19:10] Stratum difficulty set to 40000 (40)
[2017-12-15 10:19:10] GPU #0: EVGA GTX 1080 Ti, 10438 MB available, 28 SMX
[2017-12-15 10:19:10] GPU #0: 1792 threads (10.75) with 112 blocks
[2017-12-15 10:19:10] GPU #0: out of memory scanhash_cryptonight line 85

I'm running a stock 1080 ti FTW 3, and this is the first time I've seen this memory error.

**Comment by UselessGuru** [comment]
Which CryptoNight miner is this?
Try reducing the threads x blocks, it is too big.
My GTX 1080ti can run FireIce with '"threads" : 53, "blocks" : 84', XMRig with ' --cuda-launch=64x72'

**Comment by nemosminer** [comment]
XMRig is high performance Monero (XMR) NVIDIA miner, with the official full Windows support.

https://github.com/xmrig/xmrig-nvidia

**Comment by TerraBad** [comment]
Copy and pasted from [Bitcointalk](https://bitcointalk.org/index.php?topic=1777336.1780).... 

> I asked because I was getting out of memory errors when it was trying to benchmark cryptonight on MPH.  I originally thought I needed to update ccminer-Tpruvot that your script used.  I finally found out that the intensity setting was missing or too high (default).
> 
> If you can verify that it does the same to you, can you fix it in your next release?  I fixed it by editing the CcminerTpruvot.ps1 file on this line:
> 
> from:
> "cryptonight" = " -d $SelGPUCC" #Cryptonight
> 
> to:
> "cryptonight" = " -i 10 -d $SelGPUCC" #Cryptonight
> 
> That was the highest intensity without causing the out of memory error.

This fixed cryptonight for me

**Comment by nemosminer** [comment]
cryptonight" = " -i 10 -d $SelGPUCC

done:

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/34067202-878f1684-e1d3-11e7-8d08-843ff1b6e95b.png)

**Comment by joesixpack** [comment]
Got it working with -I 1, so the flaw is with tpruvot.  Are we sure that is the best miner?  I've never used it for mining cryptonight.  Xmrig and newest Xm-Stak are buggy in various ways; I've been fine and stable with the older XM-Stak.

**Comment by joesixpack** [comment]
> My GTX 1080ti can run FireIce with '"threads" : 53, "blocks" : 84', XMRig with ' --cuda-launch=64x72'

Did you determine that to be optimal?  Because the autosettings suggest 35 threads and 84  blocks.

Although pretty, XMRig has problems with certain pools on cryptonight and is slower.  Don't advise using it at current time.
