### ISSUE TITLE
Better miner for lyra2Z

### ISSUE THREAD

**Issue by maxgamurar** [nemosminer/NemosMiner-v2.2.2#76]
Hello
NVIDIA:
- https://github.com/djm34/ccminer-msvc2015/releases/ (by djm34)
(Fixed inefficient bug resulting lower hashrate on pools, compiled with latest cuda. djm34 binary is highly recommended than other ccminer releases)
The current gain of hashrate is of the order of 20%

**Comment by nemosminer** [comment]
nope:

https://github.com/nemosminer/NemosMiner-v2.2.2/issues/66

**Comment by maxgamurar** [comment]
@nemosminer tpruvot miner real hashrate on pool is  30-40% lower than reported in cli ui.
With djm34 it matches 100% but with higher invalid shares. Even though real profit is much higher
