### ISSUE TITLE
WebRequest are cached which screws up profitability data

### ISSUE THREAD

**Issue by needamailaddress** [nemosminer/NemosMiner-v2.2.2#80]
As an FYI

I had weird results with profitability data using MPH on several machines running at the same time causing NemosMiner to take the wrong decisions.

I edited ./Pools/miningpoolhub.ps1 to add "-Headers @{"Cache-Control"="no-cache"}" to the WebRequest and bingo... all machines see current and no cached data.

Final code section is:
`try
{
    $MiningPoolHub_Request = Invoke-WebRequest "https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics" -UseBasicParsing -Headers @{"Cache-Control"="no-cache"} | ConvertFrom-Json
}
catch
{
    return
}`

**Comment by nemosminer** [comment]
thankyou

**Comment by nemosminer** [comment]
done thank you @needamailaddress

**Comment by aaronsace** [comment]
This appears to make no difference. Has any tested it? 

```
$test1 = Invoke-WebRequest "https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics" -UseBasicParsing -Headers @{"Cache-Control"="no-cache"} | ConvertFrom-Json

Measure-Command {
    do {
        sleep 60
        $test2 = Invoke-WebRequest "https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics" -UseBasicParsing -Headers @{"Cache-Control"="no-cache"} | ConvertFrom-Json
    } while ((Compare-Object $test1.return.profit $test2.return.profit).Count -eq 0)
}
```
