### ISSUE TITLE
PS>TerminatingError(Invoke-WebRequest)

### ISSUE THREAD

**Issue by mahpoul22** [nemosminer/NemosMiner-v2.2.2#86]
Hey Everybody & @nemosminer 

I got this issue, first time use of the new version of Nemos Miner, 1.7.3 work fine.

Here is the full log

Thank you

Windows PowerShell transcript start
Start time: 20171215195353
Username: 
RunAs User: 
Machine:  (Microsoft Windows NT 10.0.15063.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle minimized -command &.\NemosMiner-v2.2.2.ps1 -SelGPUEWBF '0' -SelGPUCC '0' -Currency EUR -Passwordcurrency BTC -interval 120 -Username Mahpoul22 -Workername GPU -Location EU -PoolName miningpoolhub -Type nvidia -Algorithm cryptonight,lyra2z,skein,equihash,groestl,MyriadGroestl,Lyra2RE2,neoscrypt -Donate 0
Process ID: 5644
PSVersion: 5.1.15063.786
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.786
BuildVersion: 10.0.15063.786
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

Transcript started, output file is .\Logs\2017-12-15_19-53-52.txt

PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (522) Origin Connection Time-out."

**Comment by nemosminer** [comment]
try 2.3-beta

**Comment by mahpoul22** [comment]
Where can I find a link for it @nemosminer ?

**Comment by louislewis2** [comment]
I just downloaded the latest version as suggested above, getting the same error as noted above. Any ideas?
